server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: server1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server2:8762/eureka/
