// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upload.proto

package cn.my.app.grpc.upload;

public interface ChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:upload.Chunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes Content = 1;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();
}
