// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upload.proto

package cn.my.app.grpc.upload;

public interface UploadStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:upload.UploadStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 0--unknown, 1--ok, 2-failure
   * </pre>
   *
   * <code>int32 Code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string Message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string Message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
