// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upload.proto

package cn.my.app.grpc.upload;

public interface UploadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:upload.UploadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * file name with ext
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * file name with ext
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.upload.Chunk chunk = 2;</code>
   * @return Whether the chunk field is set.
   */
  boolean hasChunk();
  /**
   * <code>.upload.Chunk chunk = 2;</code>
   * @return The chunk.
   */
  cn.my.app.grpc.upload.Chunk getChunk();
  /**
   * <code>.upload.Chunk chunk = 2;</code>
   */
  cn.my.app.grpc.upload.ChunkOrBuilder getChunkOrBuilder();
}
