// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upload.proto

package cn.my.app.grpc.upload;

public final class Upload {
  private Upload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_upload_UploadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_upload_UploadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_upload_Chunk_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_upload_Chunk_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_upload_UploadStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_upload_UploadStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014upload.proto\022\006upload\";\n\rUploadRequest\022" +
      "\014\n\004name\030\001 \001(\t\022\034\n\005chunk\030\002 \001(\0132\r.upload.Ch" +
      "unk\"\030\n\005Chunk\022\017\n\007Content\030\001 \001(\014\"-\n\014UploadS" +
      "tatus\022\014\n\004Code\030\001 \001(\005\022\017\n\007Message\030\002 \001(\t2J\n\r" +
      "UploadService\0229\n\006Upload\022\025.upload.UploadR" +
      "equest\032\024.upload.UploadStatus\"\000(\001B\037\n\025cn.m" +
      "y.app.grpc.uploadP\001\242\002\003UPDb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_upload_UploadRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_upload_UploadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_upload_UploadRequest_descriptor,
        new java.lang.String[] { "Name", "Chunk", });
    internal_static_upload_Chunk_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_upload_Chunk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_upload_Chunk_descriptor,
        new java.lang.String[] { "Content", });
    internal_static_upload_UploadStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_upload_UploadStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_upload_UploadStatus_descriptor,
        new java.lang.String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
