// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: series.proto

package com.my.proto;

public final class GenSeriesData {
  private GenSeriesData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface series_dataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:series_data)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string bmSeriesId = 1;</code>
     * @return The bmSeriesId.
     */
    java.lang.String getBmSeriesId();
    /**
     * <code>string bmSeriesId = 1;</code>
     * @return The bytes for bmSeriesId.
     */
    com.google.protobuf.ByteString
        getBmSeriesIdBytes();

    /**
     * <code>int64 seriesNumber = 2;</code>
     * @return The seriesNumber.
     */
    long getSeriesNumber();

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>int32 numOfImages = 4;</code>
     * @return The numOfImages.
     */
    int getNumOfImages();

    /**
     * <code>string instanceUID = 5;</code>
     * @return The instanceUID.
     */
    java.lang.String getInstanceUID();
    /**
     * <code>string instanceUID = 5;</code>
     * @return The bytes for instanceUID.
     */
    com.google.protobuf.ByteString
        getInstanceUIDBytes();

    /**
     * <code>repeated string pacsNames = 6;</code>
     * @return A list containing the pacsNames.
     */
    java.util.List<java.lang.String>
        getPacsNamesList();
    /**
     * <code>repeated string pacsNames = 6;</code>
     * @return The count of pacsNames.
     */
    int getPacsNamesCount();
    /**
     * <code>repeated string pacsNames = 6;</code>
     * @param index The index of the element to return.
     * @return The pacsNames at the given index.
     */
    java.lang.String getPacsNames(int index);
    /**
     * <code>repeated string pacsNames = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the pacsNames at the given index.
     */
    com.google.protobuf.ByteString
        getPacsNamesBytes(int index);
  }
  /**
   * Protobuf type {@code series_data}
   */
  public static final class series_data extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:series_data)
      series_dataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use series_data.newBuilder() to construct.
    private series_data(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private series_data() {
      bmSeriesId_ = "";
      description_ = "";
      instanceUID_ = "";
      pacsNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new series_data();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private series_data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              bmSeriesId_ = s;
              break;
            }
            case 16: {

              seriesNumber_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 32: {

              numOfImages_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              instanceUID_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                pacsNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              pacsNames_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          pacsNames_ = pacsNames_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.my.proto.GenSeriesData.internal_static_series_data_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.my.proto.GenSeriesData.internal_static_series_data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.my.proto.GenSeriesData.series_data.class, com.my.proto.GenSeriesData.series_data.Builder.class);
    }

    public static final int BMSERIESID_FIELD_NUMBER = 1;
    private volatile java.lang.Object bmSeriesId_;
    /**
     * <code>string bmSeriesId = 1;</code>
     * @return The bmSeriesId.
     */
    @java.lang.Override
    public java.lang.String getBmSeriesId() {
      java.lang.Object ref = bmSeriesId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bmSeriesId_ = s;
        return s;
      }
    }
    /**
     * <code>string bmSeriesId = 1;</code>
     * @return The bytes for bmSeriesId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBmSeriesIdBytes() {
      java.lang.Object ref = bmSeriesId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bmSeriesId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERIESNUMBER_FIELD_NUMBER = 2;
    private long seriesNumber_;
    /**
     * <code>int64 seriesNumber = 2;</code>
     * @return The seriesNumber.
     */
    @java.lang.Override
    public long getSeriesNumber() {
      return seriesNumber_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMOFIMAGES_FIELD_NUMBER = 4;
    private int numOfImages_;
    /**
     * <code>int32 numOfImages = 4;</code>
     * @return The numOfImages.
     */
    @java.lang.Override
    public int getNumOfImages() {
      return numOfImages_;
    }

    public static final int INSTANCEUID_FIELD_NUMBER = 5;
    private volatile java.lang.Object instanceUID_;
    /**
     * <code>string instanceUID = 5;</code>
     * @return The instanceUID.
     */
    @java.lang.Override
    public java.lang.String getInstanceUID() {
      java.lang.Object ref = instanceUID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instanceUID_ = s;
        return s;
      }
    }
    /**
     * <code>string instanceUID = 5;</code>
     * @return The bytes for instanceUID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInstanceUIDBytes() {
      java.lang.Object ref = instanceUID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instanceUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACSNAMES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList pacsNames_;
    /**
     * <code>repeated string pacsNames = 6;</code>
     * @return A list containing the pacsNames.
     */
    public com.google.protobuf.ProtocolStringList
        getPacsNamesList() {
      return pacsNames_;
    }
    /**
     * <code>repeated string pacsNames = 6;</code>
     * @return The count of pacsNames.
     */
    public int getPacsNamesCount() {
      return pacsNames_.size();
    }
    /**
     * <code>repeated string pacsNames = 6;</code>
     * @param index The index of the element to return.
     * @return The pacsNames at the given index.
     */
    public java.lang.String getPacsNames(int index) {
      return pacsNames_.get(index);
    }
    /**
     * <code>repeated string pacsNames = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the pacsNames at the given index.
     */
    public com.google.protobuf.ByteString
        getPacsNamesBytes(int index) {
      return pacsNames_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBmSeriesIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bmSeriesId_);
      }
      if (seriesNumber_ != 0L) {
        output.writeInt64(2, seriesNumber_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
      }
      if (numOfImages_ != 0) {
        output.writeInt32(4, numOfImages_);
      }
      if (!getInstanceUIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, instanceUID_);
      }
      for (int i = 0; i < pacsNames_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, pacsNames_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBmSeriesIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bmSeriesId_);
      }
      if (seriesNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, seriesNumber_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
      }
      if (numOfImages_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, numOfImages_);
      }
      if (!getInstanceUIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, instanceUID_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < pacsNames_.size(); i++) {
          dataSize += computeStringSizeNoTag(pacsNames_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPacsNamesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.my.proto.GenSeriesData.series_data)) {
        return super.equals(obj);
      }
      com.my.proto.GenSeriesData.series_data other = (com.my.proto.GenSeriesData.series_data) obj;

      if (!getBmSeriesId()
          .equals(other.getBmSeriesId())) return false;
      if (getSeriesNumber()
          != other.getSeriesNumber()) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (getNumOfImages()
          != other.getNumOfImages()) return false;
      if (!getInstanceUID()
          .equals(other.getInstanceUID())) return false;
      if (!getPacsNamesList()
          .equals(other.getPacsNamesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BMSERIESID_FIELD_NUMBER;
      hash = (53 * hash) + getBmSeriesId().hashCode();
      hash = (37 * hash) + SERIESNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSeriesNumber());
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + NUMOFIMAGES_FIELD_NUMBER;
      hash = (53 * hash) + getNumOfImages();
      hash = (37 * hash) + INSTANCEUID_FIELD_NUMBER;
      hash = (53 * hash) + getInstanceUID().hashCode();
      if (getPacsNamesCount() > 0) {
        hash = (37 * hash) + PACSNAMES_FIELD_NUMBER;
        hash = (53 * hash) + getPacsNamesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.my.proto.GenSeriesData.series_data parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.my.proto.GenSeriesData.series_data parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.my.proto.GenSeriesData.series_data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.my.proto.GenSeriesData.series_data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.my.proto.GenSeriesData.series_data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.my.proto.GenSeriesData.series_data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.my.proto.GenSeriesData.series_data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.my.proto.GenSeriesData.series_data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.my.proto.GenSeriesData.series_data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.my.proto.GenSeriesData.series_data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.my.proto.GenSeriesData.series_data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.my.proto.GenSeriesData.series_data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.my.proto.GenSeriesData.series_data prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code series_data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:series_data)
        com.my.proto.GenSeriesData.series_dataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.my.proto.GenSeriesData.internal_static_series_data_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.my.proto.GenSeriesData.internal_static_series_data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.my.proto.GenSeriesData.series_data.class, com.my.proto.GenSeriesData.series_data.Builder.class);
      }

      // Construct using com.my.proto.GenSeriesData.series_data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bmSeriesId_ = "";

        seriesNumber_ = 0L;

        description_ = "";

        numOfImages_ = 0;

        instanceUID_ = "";

        pacsNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.my.proto.GenSeriesData.internal_static_series_data_descriptor;
      }

      @java.lang.Override
      public com.my.proto.GenSeriesData.series_data getDefaultInstanceForType() {
        return com.my.proto.GenSeriesData.series_data.getDefaultInstance();
      }

      @java.lang.Override
      public com.my.proto.GenSeriesData.series_data build() {
        com.my.proto.GenSeriesData.series_data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.my.proto.GenSeriesData.series_data buildPartial() {
        com.my.proto.GenSeriesData.series_data result = new com.my.proto.GenSeriesData.series_data(this);
        int from_bitField0_ = bitField0_;
        result.bmSeriesId_ = bmSeriesId_;
        result.seriesNumber_ = seriesNumber_;
        result.description_ = description_;
        result.numOfImages_ = numOfImages_;
        result.instanceUID_ = instanceUID_;
        if (((bitField0_ & 0x00000001) != 0)) {
          pacsNames_ = pacsNames_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pacsNames_ = pacsNames_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.my.proto.GenSeriesData.series_data) {
          return mergeFrom((com.my.proto.GenSeriesData.series_data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.my.proto.GenSeriesData.series_data other) {
        if (other == com.my.proto.GenSeriesData.series_data.getDefaultInstance()) return this;
        if (!other.getBmSeriesId().isEmpty()) {
          bmSeriesId_ = other.bmSeriesId_;
          onChanged();
        }
        if (other.getSeriesNumber() != 0L) {
          setSeriesNumber(other.getSeriesNumber());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getNumOfImages() != 0) {
          setNumOfImages(other.getNumOfImages());
        }
        if (!other.getInstanceUID().isEmpty()) {
          instanceUID_ = other.instanceUID_;
          onChanged();
        }
        if (!other.pacsNames_.isEmpty()) {
          if (pacsNames_.isEmpty()) {
            pacsNames_ = other.pacsNames_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePacsNamesIsMutable();
            pacsNames_.addAll(other.pacsNames_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.my.proto.GenSeriesData.series_data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.my.proto.GenSeriesData.series_data) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object bmSeriesId_ = "";
      /**
       * <code>string bmSeriesId = 1;</code>
       * @return The bmSeriesId.
       */
      public java.lang.String getBmSeriesId() {
        java.lang.Object ref = bmSeriesId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bmSeriesId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string bmSeriesId = 1;</code>
       * @return The bytes for bmSeriesId.
       */
      public com.google.protobuf.ByteString
          getBmSeriesIdBytes() {
        java.lang.Object ref = bmSeriesId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bmSeriesId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string bmSeriesId = 1;</code>
       * @param value The bmSeriesId to set.
       * @return This builder for chaining.
       */
      public Builder setBmSeriesId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bmSeriesId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string bmSeriesId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBmSeriesId() {
        
        bmSeriesId_ = getDefaultInstance().getBmSeriesId();
        onChanged();
        return this;
      }
      /**
       * <code>string bmSeriesId = 1;</code>
       * @param value The bytes for bmSeriesId to set.
       * @return This builder for chaining.
       */
      public Builder setBmSeriesIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bmSeriesId_ = value;
        onChanged();
        return this;
      }

      private long seriesNumber_ ;
      /**
       * <code>int64 seriesNumber = 2;</code>
       * @return The seriesNumber.
       */
      @java.lang.Override
      public long getSeriesNumber() {
        return seriesNumber_;
      }
      /**
       * <code>int64 seriesNumber = 2;</code>
       * @param value The seriesNumber to set.
       * @return This builder for chaining.
       */
      public Builder setSeriesNumber(long value) {
        
        seriesNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 seriesNumber = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeriesNumber() {
        
        seriesNumber_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int numOfImages_ ;
      /**
       * <code>int32 numOfImages = 4;</code>
       * @return The numOfImages.
       */
      @java.lang.Override
      public int getNumOfImages() {
        return numOfImages_;
      }
      /**
       * <code>int32 numOfImages = 4;</code>
       * @param value The numOfImages to set.
       * @return This builder for chaining.
       */
      public Builder setNumOfImages(int value) {
        
        numOfImages_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numOfImages = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumOfImages() {
        
        numOfImages_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object instanceUID_ = "";
      /**
       * <code>string instanceUID = 5;</code>
       * @return The instanceUID.
       */
      public java.lang.String getInstanceUID() {
        java.lang.Object ref = instanceUID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          instanceUID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string instanceUID = 5;</code>
       * @return The bytes for instanceUID.
       */
      public com.google.protobuf.ByteString
          getInstanceUIDBytes() {
        java.lang.Object ref = instanceUID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instanceUID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string instanceUID = 5;</code>
       * @param value The instanceUID to set.
       * @return This builder for chaining.
       */
      public Builder setInstanceUID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        instanceUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string instanceUID = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstanceUID() {
        
        instanceUID_ = getDefaultInstance().getInstanceUID();
        onChanged();
        return this;
      }
      /**
       * <code>string instanceUID = 5;</code>
       * @param value The bytes for instanceUID to set.
       * @return This builder for chaining.
       */
      public Builder setInstanceUIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        instanceUID_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList pacsNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePacsNamesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          pacsNames_ = new com.google.protobuf.LazyStringArrayList(pacsNames_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string pacsNames = 6;</code>
       * @return A list containing the pacsNames.
       */
      public com.google.protobuf.ProtocolStringList
          getPacsNamesList() {
        return pacsNames_.getUnmodifiableView();
      }
      /**
       * <code>repeated string pacsNames = 6;</code>
       * @return The count of pacsNames.
       */
      public int getPacsNamesCount() {
        return pacsNames_.size();
      }
      /**
       * <code>repeated string pacsNames = 6;</code>
       * @param index The index of the element to return.
       * @return The pacsNames at the given index.
       */
      public java.lang.String getPacsNames(int index) {
        return pacsNames_.get(index);
      }
      /**
       * <code>repeated string pacsNames = 6;</code>
       * @param index The index of the value to return.
       * @return The bytes of the pacsNames at the given index.
       */
      public com.google.protobuf.ByteString
          getPacsNamesBytes(int index) {
        return pacsNames_.getByteString(index);
      }
      /**
       * <code>repeated string pacsNames = 6;</code>
       * @param index The index to set the value at.
       * @param value The pacsNames to set.
       * @return This builder for chaining.
       */
      public Builder setPacsNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePacsNamesIsMutable();
        pacsNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pacsNames = 6;</code>
       * @param value The pacsNames to add.
       * @return This builder for chaining.
       */
      public Builder addPacsNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePacsNamesIsMutable();
        pacsNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pacsNames = 6;</code>
       * @param values The pacsNames to add.
       * @return This builder for chaining.
       */
      public Builder addAllPacsNames(
          java.lang.Iterable<java.lang.String> values) {
        ensurePacsNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pacsNames_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pacsNames = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPacsNames() {
        pacsNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string pacsNames = 6;</code>
       * @param value The bytes of the pacsNames to add.
       * @return This builder for chaining.
       */
      public Builder addPacsNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensurePacsNamesIsMutable();
        pacsNames_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:series_data)
    }

    // @@protoc_insertion_point(class_scope:series_data)
    private static final com.my.proto.GenSeriesData.series_data DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.my.proto.GenSeriesData.series_data();
    }

    public static com.my.proto.GenSeriesData.series_data getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<series_data>
        PARSER = new com.google.protobuf.AbstractParser<series_data>() {
      @java.lang.Override
      public series_data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new series_data(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<series_data> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<series_data> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.my.proto.GenSeriesData.series_data getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_series_data_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_series_data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014series.proto\"\211\001\n\013series_data\022\022\n\nbmSeri" +
      "esId\030\001 \001(\t\022\024\n\014seriesNumber\030\002 \001(\003\022\023\n\013desc" +
      "ription\030\003 \001(\t\022\023\n\013numOfImages\030\004 \001(\005\022\023\n\013in" +
      "stanceUID\030\005 \001(\t\022\021\n\tpacsNames\030\006 \003(\tB\035\n\014co" +
      "m.my.protoB\rGenSeriesDatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_series_data_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_series_data_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_series_data_descriptor,
        new java.lang.String[] { "BmSeriesId", "SeriesNumber", "Description", "NumOfImages", "InstanceUID", "PacsNames", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
