server:
  port: 8002
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://server1:8761/eureka,http://server2:8762/eureka  ## 注册到 eureka 
spring:
  application:
    name: single-customer 
