// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: download.proto

package cn.my.app.grpc.download;

public interface ChunkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:download.Chunk)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes content = 1;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>int32 blockSeq = 2;</code>
   * @return The blockSeq.
   */
  int getBlockSeq();
}
