// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: download.proto

package cn.my.app.grpc.download;

public interface DownloadRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:download.DownloadRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * file name with ext
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * file name with ext
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
