// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: download.proto

package cn.my.app.grpc.download;

public interface DownloadResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:download.DownloadResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * file name with ext
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * file name with ext
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.download.Chunk chunk = 2;</code>
   * @return Whether the chunk field is set.
   */
  boolean hasChunk();
  /**
   * <code>.download.Chunk chunk = 2;</code>
   * @return The chunk.
   */
  cn.my.app.grpc.download.Chunk getChunk();
  /**
   * <code>.download.Chunk chunk = 2;</code>
   */
  cn.my.app.grpc.download.ChunkOrBuilder getChunkOrBuilder();

  /**
   * <code>.download.DownloadStatus downloadStatus = 3;</code>
   * @return Whether the downloadStatus field is set.
   */
  boolean hasDownloadStatus();
  /**
   * <code>.download.DownloadStatus downloadStatus = 3;</code>
   * @return The downloadStatus.
   */
  cn.my.app.grpc.download.DownloadStatus getDownloadStatus();
  /**
   * <code>.download.DownloadStatus downloadStatus = 3;</code>
   */
  cn.my.app.grpc.download.DownloadStatusOrBuilder getDownloadStatusOrBuilder();
}
